version: '3'

services:
  mysql:
    image: mysql:5.7.36
    platform: linux/amd64
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    ports:
      - "3307:3306"
  redis:
    image: redis:4.0.14-alpine
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/webapp:delegated
    depends_on:
      - mysql
      - redis
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  db_volume:
